import Head from "next/head";
import useStyles from "../404Comp/styles";
import Link from "next/link";
import React from "react";
import { Card, CardContent, Typography } from "@material-ui/core";
import { useSelector } from "react-redux";
import { userDataSelector } from "../../redux/selectors/selector";

export default function CardPageContent() {
  const classes = useStyles();
  const data = useSelector(userDataSelector);

  const FirstName = data.localizedFirstName;
  const LastName = data.localizedLastName;
  const linkedInImage =
    data.profilePicture["displayImage~"].elements[1].identifiers[0].identifier;

  return (
    <div>
      <Head>
        <title>Card page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.card}>
        <Card>
          <CardContent className={classes.cardContent}>
            <h1 className={classes.title}>LinkedIn Card</h1>
            <div className={classes.profilePictureWrap}>
              <img
                className={classes.profilePicture}
                src={linkedInImage}
                alt="LinkedIn Image"
              ></img>
            </div>
            <Typography>First Name: {FirstName}</Typography>
            <Typography>Last Name: {LastName} </Typography>
            <Link href="/">
              <a>Back to home</a>
            </Link>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
