import Head from "next/head";
import useStyles from "../404Comp/styles";
import { AxiosResponse } from "axios";
import { ICardProps } from "../types";
import Link from "next/link";

export default function CardPageContent({ props }: ICardProps) {
  const classes = useStyles();
  const stringifyLinkedinUserData = JSON.stringify(
    props.linkedinUserData,
    null,
    2
  );

  return (
    <div className={classes.navLinks}>
      <Head>
        <title>Card page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={classes.title}>Card Page</h1>
      <p>{stringifyLinkedinUserData}</p>
      <Link href="/">
        <a>Back to home</a>
      </Link>
    </div>
  );
}
