import Head from "next/head";
import Link from "next/link";
import useStyles from "../404Comp/styles";

export default function HomePageContent() {
  const classes = useStyles();
  return (
    <div>
      <Head>
        <title>Sign In page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={classes.title}>Sign In Page</h1>

      <div className={classes.navLinks}>
        <Link href="/404page">
          <a>404 page</a>
        </Link>
        <Link
          href={`https://www.linkedin.com/oauth/v2/authorization?response_type=code&state=123&scope=r_liteprofile&client_id=${process.env.NEXT_PUBLIC_CLIENT_ID}&redirect_uri=${process.env.NEXT_PUBLIC_REDIRECT_URL}`}
        >
          <a>LinkedIn SignIn</a>
        </Link>
      </div>
    </div>
  );
}
