import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function HomeComp() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign In page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Sign In Page</h1>

      <div className={styles.input}>
        <a
          href={`https://www.linkedin.com/oauth/v2/authorization?response_type=code&state=123&scope=r_liteprofile&client_id=${process.env.NEXT_PUBLIC_CLIENT_ID}&redirect_uri=${process.env.NEXT_PUBLIC_REDIRECT_URL}`}
        >
          LinkedIn signin
        </a>
        <a href={`http://localhost:3000/404page`}>Go to 404page</a>
      </div>
    </div>
  );
}
