import useStyles from "./styles";
import React from "react";
import {
  Typography,
  Button,
  List,
  ListItem,
  ListItemText,
  Drawer,
} from "@material-ui/core";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import MenuIcon from "@material-ui/icons/Menu";
import { IAnchor } from "../types";

export default function Page404Content() {
  const classes = useStyles();

  const [state, setState] = React.useState({
    right: false,
  });

  const toggleDrawer =
    (open: boolean) => (event: React.KeyboardEvent | React.MouseEvent) => {
      if (
        event.type === "keydown" &&
        ((event as React.KeyboardEvent).key === "Tab" ||
          (event as React.KeyboardEvent).key === "Shift")
      ) {
        return;
      }

      setState({ right: open });
    };

  const list = () => (
    <div
      role="presentation"
      onClick={toggleDrawer(false)}
      onKeyDown={toggleDrawer(false)}
    >
      <List>
        {["Pricing", "Blog", "DashBoard"].map((text) => (
          <ListItem button key={text}>
            <ListItemText primary={text} />
          </ListItem>
        ))}
      </List>
    </div>
  );

  return (
    <div className={classes.container}>
      <Head>
        <title>404 page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.header}>
        <div className={classes.groupLogo}>
          <Image
            width="72px"
            height="50px"
            src="/GroupLogo.svg"
            alt="Group Logo"
          />
        </div>
        <div>
          <div className={classes.menuButton}>
            <Button
              onClick={toggleDrawer(true)}
              startIcon={<MenuIcon />}
              size="large"
              color="inherit"
            ></Button>
            <Drawer
              anchor="right"
              open={state["right"]}
              onClose={toggleDrawer(false)}
            >
              {list()}
            </Drawer>
          </div>
          <div className={classes.topButtons}>
            <Button className={classes.pricing}>Pricing</Button>
            <Button className={classes.blog}>Blog</Button>
            <Button className={classes.dashboard}>Dashboard</Button>
          </div>
        </div>
      </div>
      <div className={classes.middleContent}>
        <div className={classes.group404}>
          <Image
            width="500px"
            height="260px"
            src="/Group404.svg"
            alt="Group 404"
          />
        </div>
        <div className={classes.headerInfoDiv}>
          <Typography className={classes.headerInfo}>Page not found</Typography>
        </div>
        <div className={classes.descriptionInfoDiv}>
          <Typography className={classes.descriptionInfo}>
            The page that you’re looking for is not found. Try going back to the
            homepage
          </Typography>
        </div>

        <Link href="/">
          <a className={classes.homeButton}>Back to home</a>
        </Link>
      </div>
      <div>
        <div className={classes.footer}>
          <div className={classes.copyrightDiv}>
            <Typography className={classes.copyright}>
              Copyright 2020 © All rights Reserved
            </Typography>
          </div>
          <div className={classes.footerRightPart}>
            <div className={classes.bottomLinks}>
              <div className={classes.privacyDiv}>
                <Typography className={classes.privacy}>Privacy</Typography>
              </div>

              <div className={classes.termsConditionsDiv}>
                <Typography className={classes.termsConditions}>
                  Terms & Conditions
                </Typography>
              </div>
              <div className={classes.cookiePolicyDiv}>
                <Typography className={classes.cookiePolicy}>
                  Cookie policy
                </Typography>
              </div>
            </div>
            <div className={classes.socialIcons}>
              <div className={classes.twitterLogo}>
                <Image
                  width="32px"
                  height="26px"
                  src="/Twitter.svg"
                  alt="Twitter logo"
                />
              </div>
              <div className={classes.discordLogo}>
                <Image
                  width="23px"
                  height="26px"
                  src="/Discord.svg"
                  alt="Discord logo"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
