import useStyles from "./styles";
import Head from "next/head";
import Page404Content from "./Content/content";
import Header from "./Header/header";
import Footer from "./Footer/footer";

export default function Page404Wrap() {
  const classes = useStyles();

  return (
    <div className={classes.container}>
      <Head>
        <title>404 page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Page404Content />
      <Footer />
    </div>
  );
}
