import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios, { AxiosResponse } from "axios";
import { getURL } from "next/dist/next-server/lib/utils";
import { GetServerSideProps } from "next";

export default function Cardpage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Card page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Card Page</h1>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const code = context.query.code;
  const accessToken: AxiosResponse = await axios.get(
    "https://www.linkedin.com/oauth/v2/accessToken",
    {
      params: {
        grant_type: "authorization_code",
        code: code,
        client_id: "",
        client_secret: "",
        redirect_uri: "http://localhost:3000/cardpage",
      },
    }
  );

  interface answerType {
    profilePicture: {
      displayImage: string;
    };
    firstName: {
      localized: {};
      preferredLocale: {};
    };
    lastName: {
      localized: {};
      preferredLocale: {};
    };
    id: string;
    localizedFirstName: string;
    localizedLastName: string;
  }

  const answer: AxiosResponse<answerType> = await axios.get(
    "https://api.linkedin.com/v2/me",
    {
      headers: {
        Authorization: `Bearer ${accessToken.data.access_token}`,
      },
    }
  );

  console.log("Answer --- ", answer.data);

  return {
    props: {},
  };
};
