import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios, { AxiosResponse } from "axios";
import { GetServerSideProps } from "next";

import { Code, IAnswerType } from "../components/types";
import { getAccessToken } from "../services/getAccessToken";
import { getUserData } from "../services/getUserData";

interface Props {
  answerr: IAnswerType;
}

export default function Cardpage(props: Props) {
  const answerrr = JSON.stringify(props.answerr, null, 2);
  const { localizedLastName, id, localizedFirstName, ...rest } = props.answerr;
  const { profilePicture, ...rest2 } = rest;
  const { displayImage } = profilePicture;

  return (
    <div className={styles.container}>
      <Head>
        <title>Card page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Card Page</h1>
      <p>{answerrr}</p>
      <p>{localizedLastName}</p>
      <p>{id}</p>
      <p>{localizedFirstName}</p>
      <p>{displayImage}</p>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const code = context.query.code;
  const accessToken = getAccessToken(code);
  const answer = getUserData(accessToken.data);

  return {
    props: { answerr: answer.data },
  };
};
