import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios, { AxiosResponse } from "axios";
import { GetServerSideProps } from "next";

import { answerType } from "../components/types";

interface Props {
  answerr: answerType;
}

export default function Cardpage(props: Props) {
  const answerrr = JSON.stringify(props.answerr, null, 2);
  const { localizedLastName, id, localizedFirstName, ...rest } = props.answerr;
  const { profilePicture, ...rest2 } = rest;
  const { displayImage } = profilePicture;

  return (
    <div className={styles.container}>
      <Head>
        <title>Card page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Card Page</h1>
      <p>{answerrr}</p>
      <p>{localizedLastName}</p>
      <p>{id}</p>
      <p>{localizedFirstName}</p>
      <p>{displayImage}</p>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const code = context.query.code;
  const accessToken: AxiosResponse = await axios.get(
    "https://www.linkedin.com/oauth/v2/accessToken",
    {
      params: {
        grant_type: "authorization_code",
        code: code,
        client_id: "785jez5b2sszz3",
        client_secret: "jVWgwjpVD90zlz6c",
        redirect_uri: "http://localhost:3000/cardpage",
      },
    }
  );

  const answer: AxiosResponse<answerType> = await axios.get(
    "https://api.linkedin.com/v2/me",
    {
      headers: {
        Authorization: `Bearer ${accessToken.data.access_token}`,
      },
    }
  );
  console.log("Answer --- ", answer.data);

  return {
    props: { answerr: answer.data },
  };
};
