import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign In page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Sign In Page</h1>

      <div className={styles.input}>
        <a href="https://www.linkedin.com/oauth/v2/authorization?response_type=code&state=123&scope=r_liteprofile&client_id=785jez5b2sszz3&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcard">
          Click here
        </a>
      </div>
    </div>
  );
}
